version: "3"

services:
  app:
    build: .
    container_name: fct-car-finder
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

